### GET All workouts
GET http://localhost:3000/api/v1/workouts

###
GET http://localhost:3000/api/v1/workouts/4a3d9aaa-608c-49a7-a004-66305ad4ab50

### Create a workout
POST http://localhost:3000/api/v1/workouts
content-type: application/json

{
  "name": "Test workout",
  "mode": "AMRAP 20",
  "equipment": [
    "rack",
    "barbell",
    "abmat"
  ],
  "exercises": [
    "15 toes to bars",
    "10 thrusters",
    "30 abmat sit-ups"
  ],
  "trainerTips": [
    "Split your toes to bars into two sets maximum",
    "Go unbroken on the thrusters",
    "Take the abmat sit-ups as a chance to normalize your breath"
  ]
}

### DELETE a workout
DELETE http://localhost:3000/api/v1/workouts/a81be81d-e36b-468f-9136-21fff902ebba

